"""
reporter/splunk_dashboard.py
Generates two files:
  1. splunk_dashboard.xml  — Simple XML dashboard importable into Splunk
  2. splunk_lookup.csv     — Findings as a CSV lookup table for the dashboard

The dashboard shows:
  - Findings by severity (pie chart)
  - OWASP API Top 10 coverage (table)
  - MITRE ATT&CK tactic breakdown (bar chart)
  - Full findings table with all fields

Import into Splunk:
  Dashboard: Settings > User Interface > Dashboards > Import
  Lookup:    Settings > Lookups > Lookup table files > Upload

New in v6.
"""

import os
import csv
import json
from datetime import datetime
from reporter import mitre_map

DASHBOARD_PATH = os.path.expanduser("~/Desktop/lab/splunk_dashboard.xml")
LOOKUP_PATH    = os.path.expanduser("~/Desktop/lab/splunk_lookup.csv")


def _severity_color(severity):
    return {
        "Critical": "0xcc0000",
        "High":     "0xff6600",
        "Medium":   "0xffcc00",
        "Low":      "0x00cc66",
        "Info":     "0x4488ff",
    }.get(severity, "0x888888")


def generate_csv(findings, output_path=LOOKUP_PATH):
    """Export findings as CSV for Splunk lookup table ingestion."""
    fieldnames = [
        "timestamp", "status", "category", "severity", "owasp",
        "mitre_id", "mitre_name", "mitre_tactic",
        "cvss_score", "cvss_vector", "detail", "request"
    ]

    timestamp = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()

        for finding in findings:
            mitre = mitre_map.get(finding["category"])
            writer.writerow({
                "timestamp":    timestamp,
                "status":       finding["status"],
                "category":     finding["category"],
                "severity":     finding.get("severity") or "N/A",
                "owasp":        finding.get("owasp", "N/A"),
                "mitre_id":     mitre["id"],
                "mitre_name":   mitre["name"],
                "mitre_tactic": mitre["tactic"],
                "cvss_score":   mitre.get("cvss_score", 0.0),
                "cvss_vector":  mitre.get("cvss_vector", "N/A"),
                "detail":       finding.get("detail", ""),
                "request":      finding.get("request", ""),
            })

    print(f"  Splunk CSV lookup → {output_path}")
    return output_path


def generate_dashboard(findings, base_url="http://localhost:3001",
                        output_path=DASHBOARD_PATH):
    """Generate Splunk Simple XML dashboard."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    vulns     = [f for f in findings if f["status"] == "VULNERABLE"]
    safes     = [f for f in findings if f["status"] == "SAFE"]

    # Severity counts
    sev_counts = {"Critical": 0, "High": 0, "Medium": 0, "Low": 0, "Info": 0}
    for f in vulns:
        sev = f.get("severity", "Info")
        if sev in sev_counts:
            sev_counts[sev] += 1

    # OWASP breakdown
    owasp_map = {}
    for f in findings:
        owasp = f.get("owasp", "Unknown")
        owasp_map[owasp] = owasp_map.get(owasp, 0) + (1 if f["status"] == "VULNERABLE" else 0)

    # MITRE tactic breakdown
    tactic_map = {}
    for f in vulns:
        mitre  = mitre_map.get(f["category"])
        tactic = mitre["tactic"]
        tactic_map[tactic] = tactic_map.get(tactic, 0) + 1

    # Build finding rows for the table panel
    finding_rows = ""
    for f in sorted(vulns, key=lambda x: ["Critical","High","Medium","Low","Info"].index(
            x.get("severity","Info")) if x.get("severity") in ["Critical","High","Medium","Low","Info"] else 99):
        mitre   = mitre_map.get(f["category"])
        color   = _severity_color(f.get("severity"))
        finding_rows += f"""
            <tr>
              <td style="color:{color};font-weight:bold;">{f.get('severity','N/A')}</td>
              <td>{f['category']}</td>
              <td>{mitre['id']} — {mitre['name']}</td>
              <td>{mitre.get('cvss_score', 'N/A')}</td>
              <td style="font-size:11px;">{f.get('detail','')[:100]}...</td>
            </tr>"""

    # Severity bar data for chart
    sev_series = "".join([
        f'<item><title>{sev}</title><value>{count}</value></item>'
        for sev, count in sev_counts.items() if count > 0
    ])

    # Tactic data
    tactic_series = "".join([
        f'<item><title>{tactic}</title><value>{count}</value></item>'
        for tactic, count in sorted(tactic_map.items(), key=lambda x: -x[1])
    ])

    xml = f"""<?xml version="1.0"?>
<dashboard version="1.1" theme="dark">
  <label>API Attack Surface Auditor — Security Dashboard</label>
  <description>
    Generated by API Attack Surface Auditor v6.0 |
    Target: {base_url} |
    Scan: {timestamp} |
    Vulnerabilities: {len(vulns)} | Passed: {len(safes)}
  </description>

  <!-- Row 1: Summary Stats -->
  <row>
    <panel>
      <single>
        <title>Total Vulnerabilities</title>
        <option name="colorBy">value</option>
        <option name="drilldown">none</option>
        <data>
          <set name="result">
            <kv><key>value</key><value>{len(vulns)}</value></kv>
          </set>
        </data>
      </single>
    </panel>
    <panel>
      <single>
        <title>Critical Findings</title>
        <data>
          <set name="result">
            <kv><key>value</key><value>{sev_counts['Critical']}</value></kv>
          </set>
        </data>
      </single>
    </panel>
    <panel>
      <single>
        <title>Passed Checks</title>
        <data>
          <set name="result">
            <kv><key>value</key><value>{len(safes)}</value></kv>
          </set>
        </data>
      </single>
    </panel>
    <panel>
      <single>
        <title>Total Checks</title>
        <data>
          <set name="result">
            <kv><key>value</key><value>{len(findings)}</value></kv>
          </set>
        </data>
      </single>
    </panel>
  </row>

  <!-- Row 2: Charts -->
  <row>
    <panel>
      <chart>
        <title>Findings by Severity</title>
        <option name="charting.chart">pie</option>
        <option name="charting.legend.placement">right</option>
        <data>
          <set name="results">
            {sev_series}
          </set>
        </data>
      </chart>
    </panel>
    <panel>
      <chart>
        <title>MITRE ATT&amp;CK Tactics</title>
        <option name="charting.chart">bar</option>
        <option name="charting.chart.orientation">horizontal</option>
        <data>
          <set name="results">
            {tactic_series}
          </set>
        </data>
      </chart>
    </panel>
  </row>

  <!-- Row 3: OWASP Coverage Table -->
  <row>
    <panel>
      <html>
        <title>OWASP API Top 10 Coverage</title>
        <![CDATA[
        <style>
          .owasp-table {{ width:100%;border-collapse:collapse;font-family:monospace;font-size:12px; }}
          .owasp-table th {{ background:#1a1a1a;color:#888;padding:8px;text-align:left; }}
          .owasp-table td {{ padding:8px;border-bottom:1px solid #222; }}
          .vuln {{ color:#ff4444; }} .safe {{ color:#00cc66; }}
        </style>
        <table class="owasp-table">
          <tr><th>OWASP Category</th><th>Status</th></tr>
          {"".join(f'<tr><td>{owasp}</td><td class="{"vuln" if count > 0 else "safe"}">{"VULNERABLE ("+str(count)+")" if count > 0 else "SAFE"}</td></tr>' for owasp, count in sorted(owasp_map.items()))}
        </table>
        ]]>
      </html>
    </panel>
  </row>

  <!-- Row 4: Full Findings Table -->
  <row>
    <panel>
      <html>
        <title>Vulnerability Details</title>
        <![CDATA[
        <style>
          .findings-table {{ width:100%;border-collapse:collapse;font-family:monospace;font-size:12px; }}
          .findings-table th {{ background:#1a1a1a;color:#888;padding:8px;text-align:left; }}
          .findings-table td {{ padding:8px;border-bottom:1px solid #1a1a1a;vertical-align:top; }}
        </style>
        <table class="findings-table">
          <tr>
            <th>Severity</th>
            <th>Category</th>
            <th>MITRE ATT&amp;CK</th>
            <th>CVSS</th>
            <th>Detail</th>
          </tr>
          {finding_rows if finding_rows else "<tr><td colspan='5' style='color:#555;'>No vulnerabilities found.</td></tr>"}
        </table>
        ]]>
      </html>
    </panel>
  </row>

  <!-- Footer -->
  <row>
    <panel>
      <html>
        <![CDATA[
        <p style="font-size:11px;color:#444;font-family:monospace;">
          Generated by API Attack Surface Auditor v6.0 &middot;
          github.com/pratham2104/api-attack-surface-auditor &middot;
          Pratham Agarwal — CS &amp; Data Science, Central Michigan University
        </p>
        ]]>
      </html>
    </panel>
  </row>

</dashboard>"""

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write(xml)

    print(f"  Splunk dashboard XML → {output_path}")
    return output_path


def generate(findings, base_url="http://localhost:3001",
             dashboard_path=DASHBOARD_PATH, lookup_path=LOOKUP_PATH):
    """Generate both Splunk outputs."""
    generate_csv(findings, output_path=lookup_path)
    generate_dashboard(findings, base_url=base_url, output_path=dashboard_path)
